// Mock data for testing the React-admin interface

export const mockSecurityEvents = [
  {
    id: 1,
    eventId: 4625,
    eventType: 'AuthenticationFailure',
    riskLevel: 'critical',
    correlationScore: 0.95,
    confidenceScore: 92,
    sourceIP: '203.0.113.45',
    destinationIP: '192.168.1.100',
    user: 'SYSTEM\\administrator',
    computer: 'WIN-SERVER01',
    process: 'lsass.exe',
    commandLine: null,
    parentProcess: 'services.exe',
    mitreTechniques: 'T1110, T1110.001',
    detectionMethod: 'Deterministic',
    summary: 'Multiple failed logon attempts detected from external IP',
    recommendedActions: 'Block source IP, investigate source location, review account security',
    ipEnrichment: {
      country: 'Russia',
      city: 'Moscow',
      asn: 'AS15169',
      organization: 'Google LLC',
      isHighRisk: true,
    },
    timestamp: '2024-01-15T10:30:00Z',
    createdAt: '2024-01-15T10:30:05Z',
    notes: '',
  },
  {
    id: 2,
    eventId: 4688,
    eventType: 'ProcessCreation',
    riskLevel: 'high',
    correlationScore: 0.73,
    confidenceScore: 85,
    sourceIP: '192.168.1.50',
    destinationIP: null,
    user: 'DOMAIN\\jsmith',
    computer: 'WIN-WS01',
    process: 'powershell.exe',
    commandLine: 'powershell.exe -ExecutionPolicy Bypass -EncodedCommand <base64>',
    parentProcess: 'cmd.exe',
    mitreTechniques: 'T1059.001, T1027',
    detectionMethod: 'LLM',
    summary: 'Suspicious PowerShell execution with encoded command',
    recommendedActions: 'Analyze encoded command, check user activity, scan for malware',
    ipEnrichment: {
      country: 'United States',
      city: 'Seattle',
      asn: 'AS8075',
      organization: 'Microsoft Corporation',
      isHighRisk: false,
    },
    timestamp: '2024-01-15T14:22:00Z',
    createdAt: '2024-01-15T14:22:03Z',
    notes: 'User reported suspicious behavior',
  },
  {
    id: 3,
    eventId: 4720,
    eventType: 'AccountCreated',
    riskLevel: 'medium',
    correlationScore: 0.45,
    confidenceScore: 78,
    sourceIP: '192.168.1.10',
    destinationIP: null,
    user: 'DOMAIN\\admin',
    computer: 'WIN-DC01',
    process: 'lsass.exe',
    commandLine: null,
    parentProcess: 'services.exe',
    mitreTechniques: 'T1136',
    detectionMethod: 'Enhanced',
    summary: 'New user account created during business hours',
    recommendedActions: 'Verify account creation was authorized, review account permissions',
    ipEnrichment: {
      country: 'United States',
      city: 'Redmond',
      asn: 'AS8075',
      organization: 'Microsoft Corporation',
      isHighRisk: false,
    },
    timestamp: '2024-01-15T09:15:00Z',
    createdAt: '2024-01-15T09:15:02Z',
    notes: 'Account created for new employee',
  },
];

export const mockComplianceReports = [
  {
    id: 1,
    framework: 'HIPAA',
    reportType: 'assessment',
    implementationPercentage: 87,
    controlCount: 18,
    implementedControls: 16,
    gapCount: 2,
    riskScore: 2.3,
    status: 'complete',
    version: '1.2',
    generated: '2024-01-15T08:00:00Z',
    validUntil: '2024-04-15T08:00:00Z',
    generatedBy: 'CastellanPro Compliance Engine',
    summary: 'Organization demonstrates strong HIPAA compliance with 87% implementation. Key gaps identified in audit logging and encryption requirements.',
    keyFindings: 'Strong administrative safeguards (100%), good physical safeguards (85%), technical safeguards need improvement (78%). Two critical gaps: comprehensive audit trail coverage and end-to-end encryption for PHI data at rest.',
    recommendations: '1. Implement comprehensive audit logging for all PHI access. 2. Deploy AES-256 encryption for all PHI storage systems. 3. Update business associate agreements. 4. Conduct quarterly security assessments.',
    nextReview: '2024-02-15T08:00:00Z',
  },
  {
    id: 2,
    framework: 'FedRAMP',
    reportType: 'gap_analysis',
    implementationPercentage: 72,
    controlCount: 325,
    implementedControls: 234,
    gapCount: 91,
    riskScore: 3.8,
    status: 'in_progress',
    version: '1.0',
    generated: '2024-01-14T16:30:00Z',
    validUntil: '2024-07-14T16:30:00Z',
    generatedBy: 'CastellanPro Compliance Engine',
    summary: 'FedRAMP Moderate baseline assessment reveals 72% compliance. Significant gaps in continuous monitoring and security control automation.',
    keyFindings: 'Access control family 89% compliant, System and communications protection 67% compliant, Continuous monitoring 45% compliant. Major gaps in automated security responses and real-time monitoring capabilities.',
    recommendations: '1. Implement automated continuous monitoring system. 2. Deploy security orchestration platform. 3. Enhance incident response automation. 4. Complete security control documentation.',
    nextReview: '2024-03-14T16:30:00Z',
  },
  {
    id: 3,
    framework: 'SOC2',
    reportType: 'audit_ready',
    implementationPercentage: 94,
    controlCount: 67,
    implementedControls: 63,
    gapCount: 4,
    riskScore: 1.2,
    status: 'complete',
    version: '2.1',
    generated: '2024-01-13T12:00:00Z',
    validUntil: '2024-06-13T12:00:00Z',
    generatedBy: 'CastellanPro Compliance Engine',
    summary: 'SOC 2 Type II readiness assessment shows excellent compliance at 94%. Organization is well-prepared for external audit.',
    keyFindings: 'Security (98%), Availability (95%), Processing integrity (92%), Confidentiality (90%). Minor gaps in change management documentation and vendor management procedures.',
    recommendations: '1. Complete change management procedure documentation. 2. Update vendor risk assessment procedures. 3. Implement automated compliance monitoring dashboard. 4. Schedule pre-audit assessment.',
    nextReview: '2024-02-13T12:00:00Z',
  },
];

export const mockSystemStatus = [
  {
    id: 1,
    component: 'CastellanPro Pipeline',
    status: 'healthy',
    isHealthy: true,
    uptime: 2592000, // 30 days
    performance: 94,
    memoryUsageMB: 245,
    memoryTotalMB: 2048,
    cpuUsagePercent: 12,
    diskUsagePercent: 35,
    diskAvailableGB: 45.2,
    threadCount: 18,
    version: '1.5.2',
    configuration: 'Production',
    environment: 'Windows Server 2022',
    deploymentMode: 'Service',
    endpoint: 'localhost:5000',
    port: 5000,
    isConnected: true,
    responseTimeMs: 23,
    lastCheck: '2024-01-15T15:30:00Z',
    startTime: '2023-12-16T08:00:00Z',
    lastRestart: '2023-12-20T02:00:00Z',
    restartCount: 2,
    healthDetails: 'All systems operational. Processing events normally.',
    lastError: null,
    lastErrorTime: null,
    dependencies: 'Qdrant, Ollama, MaxMind GeoIP',
    dependencyStatus: 'All dependencies healthy',
  },
  {
    id: 2,
    component: 'Qdrant Vector Database',
    status: 'healthy',
    isHealthy: true,
    uptime: 2678400, // 31 days
    performance: 91,
    memoryUsageMB: 1024,
    memoryTotalMB: 4096,
    cpuUsagePercent: 8,
    diskUsagePercent: 22,
    diskAvailableGB: 120.5,
    threadCount: 12,
    version: '1.7.3',
    configuration: 'Production',
    environment: 'Docker Container',
    deploymentMode: 'Container',
    endpoint: 'localhost:6333',
    port: 6333,
    isConnected: true,
    responseTimeMs: 15,
    lastCheck: '2024-01-15T15:30:00Z',
    startTime: '2023-12-15T10:00:00Z',
    lastRestart: '2023-12-15T10:00:00Z',
    restartCount: 0,
    healthDetails: 'Vector operations performing optimally. 2.3M vectors stored.',
    lastError: null,
    lastErrorTime: null,
    dependencies: 'Docker Engine',
    dependencyStatus: 'Docker healthy',
  },
  {
    id: 3,
    component: 'Security Event Detector',
    status: 'healthy',
    isHealthy: true,
    uptime: 2592000, // 30 days
    performance: 96,
    memoryUsageMB: 180,
    memoryTotalMB: 512,
    cpuUsagePercent: 5,
    diskUsagePercent: 15,
    diskAvailableGB: 89.3,
    threadCount: 8,
    version: '1.5.2',
    configuration: 'Production',
    environment: 'Embedded Service',
    deploymentMode: 'Integrated',
    endpoint: 'internal',
    port: null,
    isConnected: true,
    responseTimeMs: 5,
    lastCheck: '2024-01-15T15:30:00Z',
    startTime: '2023-12-16T08:00:00Z',
    lastRestart: '2023-12-20T02:00:00Z',
    restartCount: 2,
    healthDetails: 'Detecting security events at optimal rate. 25 rules active.',
    lastError: null,
    lastErrorTime: null,
    dependencies: 'Windows Event Log API',
    dependencyStatus: 'Event log access healthy',
  },
  {
    id: 4,
    component: 'Performance Monitor',
    status: 'warning',
    isHealthy: true,
    uptime: 2592000, // 30 days
    performance: 76,
    memoryUsageMB: 95,
    memoryTotalMB: 256,
    cpuUsagePercent: 3,
    diskUsagePercent: 8,
    diskAvailableGB: 156.8,
    threadCount: 4,
    version: '1.5.2',
    configuration: 'Production',
    environment: 'Embedded Service',
    deploymentMode: 'Integrated',
    endpoint: 'internal',
    port: null,
    isConnected: true,
    responseTimeMs: 12,
    lastCheck: '2024-01-15T15:30:00Z',
    startTime: '2023-12-16T08:00:00Z',
    lastRestart: '2024-01-10T03:00:00Z',
    restartCount: 5,
    healthDetails: 'Performance metrics collection slower than expected. Investigating bottleneck.',
    lastError: 'Timeout collecting disk metrics',
    lastErrorTime: '2024-01-15T10:22:00Z',
    dependencies: 'WMI, Performance Counters',
    dependencyStatus: 'WMI responding slowly',
  },
  {
    id: 5,
    component: 'IP Enrichment Service',
    status: 'healthy',
    isHealthy: true,
    uptime: 2592000, // 30 days
    performance: 88,
    memoryUsageMB: 156,
    memoryTotalMB: 512,
    cpuUsagePercent: 2,
    diskUsagePercent: 45,
    diskAvailableGB: 23.1,
    threadCount: 3,
    version: '1.5.2',
    configuration: 'Production',
    environment: 'Embedded Service',
    deploymentMode: 'Integrated',
    endpoint: 'internal',
    port: null,
    isConnected: true,
    responseTimeMs: 8,
    lastCheck: '2024-01-15T15:30:00Z',
    startTime: '2023-12-16T08:00:00Z',
    lastRestart: '2023-12-20T02:00:00Z',
    restartCount: 2,
    healthDetails: 'IP enrichment functioning normally. MaxMind databases current.',
    lastError: null,
    lastErrorTime: null,
    dependencies: 'MaxMind GeoIP2 Databases',
    dependencyStatus: 'GeoIP databases up to date',
  },
];